version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pharaohfolio_db
      POSTGRES_USER: pharaohfolio_user
      POSTGRES_PASSWORD: pharaohfolio_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # External port 5433 maps to internal port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharaohfolio_user -d pharaohfolio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/Pharaohfolio/.env
    volumes:
      - ./backend/Pharaohfolio:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/pharaohfolio
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/pharaohfolio:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
